export const signs = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
];

export const zodiacSigns = {
  sun: "A",
  moon: "B",
  mercury: "C",
  venus: "D",
  mars: "E",
  jupiter: "F",
  saturn: "G",
  uranus: "H",
  neptune: "I",
  pluto: "J",
  node: "L",
  northnode: "L",
  southnode: "M",
  eris: "N",
  earth: "O",
  ascendant: "P",
  midheaven: "Q",
  retrograde: "R",
  partoffortune: "S",
  chiron: "U",
  ceres: "V",
  pallas: "W",
  juno: "X",
  vesta: "Y",
  aries: "a",
  taurus: "b",
  gemini: "c",
  cancer: "d",
  leo: "e",
  virgo: "f",
  libra: "g",
  scorpio: "h",
  sagittarius: "i",
  capricorn: "j",
  aquarius: "k",
  pisces: "l",
  conjunction: "m",
  opposition: "n",
  trine: "p",
  sextile: "q",
  semisextile: "r",
  quincunx: "s",
  semisqaure: "t",
  square: "o",
  semisquare: "u",
};
