export const TextStyle = {
size:{
    xs: 'text-xs',
      sm: 'text-sm',
      base: 'text-base',
      lg: 'md:text-lg text-base',
      xl: 'md:text-xl text-lg',
      '2xl': 'md:text-2xl text-xl',
      '3xl': 'md:text-3xl text-2xl',
      '4xl': 'md:text-4xl text-3xl',
      '5xl': 'md:text-5xl text-4xl',
      '6xl': 'md:text-6xl text-5xl',
      '7xl': 'md:text-7xl text-6xl',
      '8xl': 'md:text-8xl text-7xl',
      '9xl': 'md:text-9xl text-8xl',
},
weight: {
      thin: 'font-thin',
      extralight: 'font-extralight',
      light: 'font-light',
      normal: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
      extrabold: 'font-extrabold',
      black: 'font-black',
    },
}